---
title: "BST260FinalProject"
author: "Auyon Ghosh"
date: "12/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

options(scipen=999)
```

#Load relevant packages
```{r}

library(tidyverse)
library(RCurl)
library(readxl)
library(ggplot2)
library(dslabs)
library(broom)

```

#Read in data
```{r}

NCHSCausesOfDeath <- read.csv("https://raw.githubusercontent.com/ajghosh/BST260FinalProj/master/NCHS_-_Leading_Causes_of_Death__United_States.csv")

PalmerDroughtIndex <- read.csv("https://raw.githubusercontent.com/ajghosh/BST260FinalProj/master/Palmer_Drought_Severity_Index__1895-2016.csv")

AirQualityMeasures <- read.csv("https://raw.githubusercontent.com/ajghosh/BST260FinalProj/master/Air_Quality_Measures_on_the_National_Environmental_Health_Tracking_Network.csv")

StateFIPS <- read.csv("https://raw.githubusercontent.com/ajghosh/BST260FinalProj/master/State%20FIPS%20codes.csv",header = F)

Wildfires <- read.csv("https://raw.githubusercontent.com/ajghosh/BST260FinalProj/master/Wildfires.csv")

data(murders)

currentsmoking <- read.csv("https://raw.githubusercontent.com/ajghosh/BST260FinalProj/master/Current%20Cigarette%20Use%20Among%20Adults%20(Behavior%20Risk%20Factor%20Surveillance%20System)%202017.csv")

```

#Select columns and rows of interest from each dataset
```{r}

##Limit causes of death to chronic lung disease

CLRDdeaths <- NCHSCausesOfDeath %>% 
  filter(Cause.Name=='CLRD') %>%
  select(Year,Cause.Name,State,Deaths,Age.adjusted.Death.Rate) %>%
  rename("Cause name"=Cause.Name,"deathrate"=Age.adjusted.Death.Rate,"state"=State,"year"=Year)

CLRDdeaths <- left_join(CLRDdeaths,murders, by="state")
CLRDdeaths$region <- CLRDdeaths$region %>% replace_na('United States')

##Limit Drought Index to years with mortality data

ModernPalmer <- PalmerDroughtIndex %>% filter(year %in% 1999:2017) 
MonthlyPalmer <- ModernPalmer %>% group_by(statefips,year,month) %>% summarize(monthPDSI = mean(pdsi))
YearlyPalmer <- MonthlyPalmer %>% group_by(statefips,year) %>% summarize(yearPDSI = mean(monthPDSI))

StateFIPS <- StateFIPS %>% rename("statefips"=V3,"state"=V1,"abb"=V2)###Get state names from FIPS code

YearlyPalmerState <- left_join(YearlyPalmer,StateFIPS, by="statefips")
YearlyPalmerState <- YearlyPalmerState %>% select(year,state,statefips,yearPDSI)

murders <- murders %>% select(state,region)

YearlyPalmerState <- left_join(YearlyPalmerState,murders, by="state")
YearlyPalmerState$state <- YearlyPalmerState$state %>% replace_na('DC')
YearlyPalmerState$region <-YearlyPalmerState$region %>% replace_na('South')

##Clean up Wildfires dataset
Wildfires <- Wildfires %>% rename("wildfires"=Number.of.fires,"state"=State,"acres"=Number.of.acres.burned,"year"=Year)
Wildfires <- left_join(Wildfires,murders, by="state")

Wildfires <- na.omit(Wildfires)
Wildfires <- Wildfires %>% filter(!year==2018)

##Clean up air quality data
str(AirQualityMeasures)

AirQualityMeasures<- AirQualityMeasures %>% filter(MeasureType=="Average") %>%  select(StateName,ReportYear,Value) %>% rename("state"=StateName,"year"=ReportYear,"avgPM"=Value) %>% group_by(state,year) %>% summarize(SavgPM = mean(avgPM))

##Clean up current smoking

currentsmoking <- currentsmoking %>% select(Location.Desc,Data.Value) %>% rename("state"=Location.Desc,"smoking"=Data.Value)
```

#Making a single analysis dataset
```{r}
##Combining death data and air quality data (particulate matter)
respfireairqual <- left_join(CLRDdeaths,AirQualityMeasures,by=c("state","year"))

##Adding wildfire data
respfireairqual <- left_join(respfireairqual,Wildfires,by=c("state","year")) 
respfireairqual <- respfireairqual %>% select(c(year,state,deathrate,region.x,SavgPM,wildfires,acres)) %>% rename("region"=region.x,"avgpm"=SavgPM)

##Adding drought data
respfireairqual <- left_join(respfireairqual,YearlyPalmerState,by=c("state","year","region"))
respfireairqual <- respfireairqual %>% select(year,state,region,deathrate,avgpm,wildfires,acres,yearPDSI)

##Adding 2018 smoking rates
respfireairqual <- left_join(respfireairqual,currentsmoking,by="state")

```

#Some data visualization
```{r}
##Wildfires
Wildfires %>% mutate(state = reorder(state,wildfires, FUN = median)) %>%
  ggplot() +
  geom_boxplot(aes(state,wildfires,fill=region)) +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_y_continuous(trans="log10")

Wildfires %>% mutate(state = reorder(state,acres, FUN = median)) %>% 
  ggplot() +
  geom_boxplot(aes(state,acres,fill=region)) +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_y_continuous(trans="log10")

Wildfires %>% group_by(year) %>% summarize(wildfiresYear = sum(wildfires)) %>% ggplot() +
  geom_line(aes(year,wildfiresYear))

Wildfires %>% filter(year %in% c(2010,2014,2017)) %>% mutate(state = reorder(state,wildfires, FUN = median)) %>% 
  ggplot() +
  geom_col(aes(state,wildfires,fill=region)) +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_grid(year~.) +
  scale_y_continuous(trans = "log10")

Wildfires %>% filter(year %in% c(2010,2014,2017)) %>% mutate(state = reorder(state,acres, FUN = median)) %>% 
  ggplot() +
  geom_col(aes(state,acres,fill=region)) +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_grid(year~.) +
  scale_y_continuous(trans = "log10")
  
  
##Death rate

CLRDdeaths %>% filter(State == "United States") %>% ggplot() +
  geom_line(aes(year,deathrate))

CLRDdeaths %>% filter(State == "Alabama") %>% ggplot() +
  geom_line(aes(year,deathrate))

CLRDdeaths %>% mutate(state = reorder(state, deathrate, FUN = median)) %>% 
  ggplot() +
  geom_boxplot(aes(state,deathrate,fill=region)) +
  theme(axis.text.x = element_text(angle = 90))

CLRDdeaths %>% filter(state != "United States") %>% group_by(region,year) %>% summarize(Rdeathrate = mean(deathrate)) %>% ggplot() +
  geom_line(aes(year,Rdeathrate,color=region))

#Particulate Matter (pm)

respfireairqual %>% filter(year %in% c(2000,2004,2008,2012)) %>% mutate(state = reorder(state,avgpm, FUN = median)) %>% 
  ggplot() +
  geom_col(aes(state,avgpm,fill=region)) +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_grid(year~.)

respfireairqual %>% filter(year %in% 1999:2013) %>% mutate(state = reorder(state,avgpm, FUN = median)) %>%
  ggplot() +
  geom_boxplot(aes(state,avgpm,fill=region)) +
  theme(axis.text.x = element_text(angle = 90))

#PDSI

respfireairqual %>% filter(year %in% c(2000,2004,2008,2012)) %>% mutate(state = reorder(state,yearPDSI, FUN = median)) %>% 
  ggplot() +
  geom_col(aes(state,yearPDSI,fill=region)) +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_grid(year~.)

respfireairqual %>% filter(year %in% 1999:2013) %>% mutate(state = reorder(state,yearPDSI, FUN = median)) %>%
  ggplot() +
  geom_boxplot(aes(state,yearPDSI,fill=region)) +
  theme(axis.text.x = element_text(angle = 90))

```

#Prelim analyses
```{r}

model <- lm(deathrate ~ acres + factor(region) + smoking, data=respfireairqual %>% filter(year %in% 2009:2017))
summary(model)

model2 <- lm(deathrate ~ avgpm + yearPDSI + year*factor(region) + smoking, data=respfireairqual %>% filter(year %in% 1999:2013))
summary(model2)

model3 <- lm(deathrate ~ avgpm + year*factor(region) + smoking, data=respfireairqual %>% filter(year %in% 1999:2013))
summary(model3)

```

#Instead of time series, multiple cross sections using broom
```{r}

##Effect of region over time controlling for wildfire acres
wildfiredeath <- respfireairqual %>% filter(year %in% 2009:2017) %>% select(year,region,deathrate,wildfires,acres,smoking)
wildfiredeath <- na.omit(wildfiredeath)

wildfiredeath %>% group_by(year) %>% 
  do(tidy(lm(deathrate ~ acres*factor(region) + smoking, data=.))) %>% 
  select(year,term,estimate,p.value) %>% 
  filter(term %in% c('factor(region)West','factor(region)South','factor(region)North Central')) %>% 
  ggplot() +
  geom_line(aes(year,estimate,color=term)) +
  scale_x_continuous(breaks=c(2009,2010,2011,2012,2013,2014,2015,2016,2017,2018)) +
  theme_bw()

wildfiredeath %>% group_by(year) %>% 
  do(tidy(lm(deathrate ~ wildfires*factor(region) + smoking, data=.))) %>% 
  select(year,term,estimate,p.value) %>% 
  filter(term %in% c('factor(region)West','factor(region)South','factor(region)North Central')) %>% 
  ggplot() +
  geom_line(aes(year,estimate,color=term)) +
  scale_x_continuous(breaks=c(2009,2010,2011,2012,2013,2014,2015,2016,2017,2018)) +
  theme_bw()

wildfiredeath %>% group_by(year) %>% 
  do(tidy(lm(deathrate ~ acres + factor(region) + smoking, data=.))) %>% 
  select(year,term,estimate,p.value) %>% 
  filter(term %in% c('factor(region)West','factor(region)South','factor(region)North Central')) %>% 
  ggplot() +
  geom_smooth(aes(year,estimate,color=term)) +
  scale_x_continuous(breaks=c(2009,2010,2011,2012,2013,2014,2015,2016,2017,2018)) +
  theme_bw()

##Effect of region over time controlling for PM and drought
airqualdeath <- respfireairqual %>% filter(year %in% 1999:2013) %>% 
  select(year,region,deathrate,avgpm,yearPDSI,smoking)
airqualdeath <- na.omit(airqualdeath)

airqualdeath %>% group_by(year) %>% 
  do(tidy(lm(deathrate ~ avgpm + yearPDSI + factor(region) + smoking, data=.),conf.int = TRUE)) %>% 
  select(year,term,estimate,p.value) %>% 
  filter(term %in% c(c('factor(region)West','factor(region)South','factor(region)North Central'))) %>% 
  ggplot() +
  geom_smooth(aes(year,estimate,color=term)) +
  scale_x_continuous(breaks=1999:2013) +
  theme_bw()

airqualdeath %>% group_by(year) %>% 
  do(tidy(lm(deathrate ~ avgpm + yearPDSI + factor(region) + smoking, data=.),conf.int = TRUE)) %>% 
  select(year,term,estimate,p.value) %>% 
  filter(term %in% c(c('factor(region)West','factor(region)South','factor(region)North Central'))) %>% 
  ggplot() +
  geom_line(aes(year,estimate,color=term)) +
  scale_x_continuous(breaks=1999:2013) +
  theme_bw()


```